CFLAGS = -std=c++17 -O2

ch01_sort: ch01_sort.cpp ch01_sort.h test.h
	g++ $(CFLAGS) $< -o $@

ch01_probabilistic_counting: ch01_probabilistic_counting.cpp test.h
	g++ $(CFLAGS) $< -o $@

all: ch01_sort ch01_probabilistic_counting
